[tasks.engine]
workspace = false
command = "cargo"
args = ["build", "--release", "--package", "engine"]

# ─────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────

[tasks.cli-win]
workspace = false
script_runner = "@duckscript"
script = '''
exec cargo build --release --package cli --target x86_64-pc-windows-msvc
'''

[tasks.cli-linux]
workspace = false
script_runner = "@duckscript"
script = '''
exec cross build --release --package cli --target x86_64-unknown-linux-gnu
'''

[tasks.cli]
workspace = false
dependencies = [
    "cli-win",
    "cli-linux",
]

# ─────────────────────────────────────────────
# LSP
# ─────────────────────────────────────────────

[tasks.lsp-win]
workspace = false
script_runner = "@duckscript"
script = '''
exec cargo build --release --package lsp --target x86_64-pc-windows-msvc
'''

[tasks.lsp-linux]
workspace = false
script_runner = "@duckscript"
script = '''
exec cross build --release --package lsp --target x86_64-unknown-linux-gnu
'''

[tasks.lsp]
workspace = false
dependencies = [
    "lsp-win",
    "lsp-linux",
]

# ─────────────────────────────────────────────
# WASM
# ─────────────────────────────────────────────

[tasks.wasm]
workspace = false
script_runner = "@duckscript"
script = '''
exec cargo build --release --package wasm --target wasm32-unknown-unknown
'''

# ─────────────────────────────────────────────
# All
# ─────────────────────────────────────────────

[tasks.all]
workspace = false
dependencies = [
    "engine",
    "cli",
    "wasm",
    "lsp",
]

